-- Corner data for track: ier_daytona
-- Generated by Traces app
return {
    {0.014138, 0.114742, "Corner 1"},  -- Corner 1 - Corner 1
    {0.133788, 0.210582, "Corner 3"},  -- Corner 2 - Corner 3
    {0.263763, 0.331124, "Corner 5"},  -- Corner 3 - Corner 5
    {0.344766, 0.424662, "Corner 6"},  -- Corner 4 - Corner 6
    {0.628095, 0.726602, "Bus Stop"},  -- Corner 5 - Bus Stop
}