-- Corner data for track: ier_daytona
-- Generated by Traces app
return {
    {0.014138, 0.114742},  -- Corner 1
    {},  -- Skip 2
    {0.133788, 0.214304},  -- Corner 3
    {},  -- Skip 4
    {0.263763, 0.337145},  -- Corner 5
    {0.343786, 0.424662},  -- Corner 6
    {0.629264, 0.726602},  -- Corner 7
}